# Generated by Django 6.0 on 2026-01-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featuered_image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
