# Generated by Django 6.0 on 2026-01-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_featuered_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='featuered_image',
            new_name='featured_image',
        ),
    ]
